FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
COPY . /app
WORKDIR /app
COPY run.sh /app/
RUN chmod +x /app/run.sh
CMD ["/app/run.sh"]

# run.sh
#!/bin/bash
python3 -m pip install .
python3 main.py